# Generated by Django 4.0.6 on 2023-03-11 21:28

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(blank=True, null=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, related_name='users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.JSONField(default=core.models.default_job_status)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('script', models.FileField(null=True, upload_to=core.models.job_script_file_path)),
                ('dataset_id', models.CharField(choices=[('cps_00008', 'CPS2008'), ('puf_2012', 'PUF2012')], max_length=32)),
                ('max_epsilon', models.JSONField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.PositiveIntegerField()),
                ('compute_sensitivities', models.BooleanField(default=True)),
                ('refined_epsilons', models.JSONField(default=dict)),
                ('status', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
            options={
                'ordering': ('job', 'run_id'),
                'unique_together': {('job', 'run_id')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('released', models.BooleanField(default=False)),
                ('analysis_type', models.CharField(choices=[('T', 'Table'), ('M', 'Model')], max_length=1)),
                ('analysis_name', models.CharField(max_length=255)),
                ('statistic_id', models.IntegerField()),
                ('var', models.CharField(blank=True, max_length=255)),
                ('statistic', models.CharField(max_length=255)),
                ('group', models.JSONField(blank=True)),
                ('chi', models.FloatField()),
                ('noise_90', models.FloatField()),
                ('epsilon_value', models.FloatField()),
                ('value_sanitized', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.run')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.FloatField(default=100)),
                ('release', models.FloatField(default=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
