# Generated by Django 4.0.6 on 2023-03-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_refined_epsilons_run_epsilons'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='released_ids',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
